### PR TITLE
feat: Add new cli-based test

### PR DESCRIPTION
**Pull request by Taewan-P**
This PR includes new cli-based test. (ref. [client-py#163](https://github.com/lablup/backend.ai-client-py/pull/163), [client-py#177](https://github.com/lablup/backend.ai-client-py/pull/177))
The new cli-based test is based on JSON output.

## Checklist (All elements shown as checkmarks are arguments)
***"Not supported" means the test cannot fully verify whether it is successfully executed.***

### User
- **Add user**
    - [x] Username 
    - [x] Full name
    - [x] E-mail
    - [x] Status
    - [x] Need password change flag
    - [x] Role
    - [ ] Description (Not supported - JSON)
- **Update user**
    - [x] Username
    - [x] Full name
    - [x] Status
    - [x] Need password change flag
    - [x] Domain name
    - [ ] Password (Not supported)
    - [ ] Role (Error occurs)
    - [ ] Description (Not supported - JSON)
- **Delete user**
    - [x] E-mail
- **List user**
    - [x] List users

### Vfolder
- **Create vfolder**
    - [x] Permission
    - [ ] Group (Not supported - group error)
    - [ ] Usage mode (Not supported - JSON)
    - [ ] Quota (Not supported - JSON)
    - [ ] Allow clone (Not supported - JSON)
- **Rename vfolder**
    - [x] Old name
- **Delete vfolder**
    - [x] Existing
- **List vfolder**
    - [x] List vfolders

### Keypair
- **Create keypair**
    - [x] Admin
    - [x] Inactive
    - [x] Rate limit
- **Update keypair**
    - [x] Admin
    - [x] Active
    - [x] Rate limit
    - [ ] Resource policy (Not supported - keypair-resource-policy)
- **Delete keypair**
    - [x] Access key
- **List keypair**
    - [x] List keypairs

### Storage
- [x] **List storage**
- [x] **Storage info**

### Scaling Group
- **Add scaling group**
    - [x] Description
    - [x] Inactive
    - [x] Driver
    - [x] Scheduler
    - [ ] Driver options (Not supported - JSON)
    - [ ] Scheduler options (Not supported - JSON)
- **Update scaling group**
    - [x] Description
    - [x] Inactive
    - [x] Driver
    - [x] Scheduler
    - [ ] Driver options (Not supported - JSON)
    - [ ] Scheduler options (Not supported - JSON)
- **Delete scaling group**
    - [x] Name
- **List scaling group**
    - [x] List scaling group

### Domain
- **Create domain**
    - [x] Description
    - [x] Inactive
    - [x] Total resource slots
    - [x] Allowed vfolder hosts
    - [x] Allowed docker registries
- **Update domain**
    - [x] New name
    - [x] Description
    - [x] Inactive
    - [x] Total resource slots
    - [x] Allowed vfolder hosts
    - [x] Allowed docker registries
- **Delete domain**
    - [x] Name
- **List domain**
    - [x] List domain

### Image
- **Alias image** (Not supported - JSON)
- **Dealias image** (Not supported - JSON)
- **List image**
    - [x] List image

### Keypair Resource Policy
- **Add keypair resource policy**
    - [x] Total resource slot
    - [x] Max concurrent sessions
    - [x] Max containers per session
    - [x] Max vfolder count
    - [x] Max vfolder size
    - [x] Idle timeout
    - [x] Allowed vfolder hosts
    - [ ] Default for unspecified (Not supported - JSON)
- **Update keypair resource policy**
    - [x] Total resource slot
    - [x] Max concurrent sessions
    - [x] Max containers per session
    - [x] Max vfolder count
    - [x] Max vfolder size
    - [x] Idle timeout
    - [x] Allowed vfolder hosts
    - [ ] Default for unspecified (Not supported - JSON)
- **Delete keypair resource policy**
    - [x] Name
- **List keypair resource policy**
    - [x] List keypair resource policy

### Group
- **Add group** (Not supported)
- **Update group** (Not supported)
- **Delete group** (Not supported)
- **List group**
    - [x] List group

### CODE REVIEW

**Comment by Taewan-P** [comment]
Somehow, there is an issue with the account update.
If you try to change a monitor role or admin role account to user role, it will raise an error in CLI.
```
✘ User update has failed: unexpected error: bindparam() name 'user' is reserved for automatic usage in the VALUES or SET clause of this insert/update statement.   Please use a name other than column name when using bindparam() with insert() or update() (for example, 'b_user').
```
Also changing a role to monitor raises this error.
User -> User does not raise this error

**Comment by Taewan-P** [comment]
image
There is also an issue about vfolder listing when the vfolder has a group. Creating a vfolder with a group will not show when using `vfolder list` even with super admin account.

You can see in the picture that `testfolder_default` is not showing up when using `vfolder list`.

**Comment by Taewan-P** [comment]
For scaling group update, when you add options to the variable, you must include the description argument. Otherwise, the description that was added previously will disappear.
image

**Comment by Taewan-P** [comment]
Will continue to work with PR branch [client-py#177](https://github.com/lablup/backend.ai-client-py/pull/177). (Contains refactored domain commands)

**Comment by Taewan-P** [comment]
And for admin image commands:
```
taewanpark@Sophies-Mini client-py % backend.ai --output=json admin image list
{
  "error": "'hash'"
}
```
~There is an error in listing images.~
It is now fixed. ([ref](https://github.com/lablup/backend.ai-client-py/pull/177/commits/d04edd72e5e92e83d8113a992b150d0648d0050c))

**Comment by Taewan-P** [comment]
Group cannot be tested due to purge errors. 
```
taewanpark@Sophies-Mini client-py % backend.ai --output=json admin group purge testgroup
Are you sure? [Y/n] y
✘ BackendAPIError: 400 Bad request
  GraphQL-generated error
  ➜ Error details:
  badly formed hexadecimal UUID string
```
Creating group has no problem, but I cannot delete it.

**Review by achimnol — APPROVED** [review]
Great job!!! :+1:
I will look into the server-side errors.

**Comment by achimnol** [comment]
Just need to update the resource slot check routines when lablup/backend.ai-client-py#177 is updated to use output formatters.

**Pull request merged**
